os: linux

language: node_js
node_js: 12

cache:
  yarn: true

jobs:
  include:
    - stage: test
      addons:
        firefox: latest
        chrome: stable
      dist: trusty
      before_script:
        - export DISPLAY=:99.0
        - sh -e /etc/init.d/xvfb start
      script:
        - yarn lint
        - yarn build
        - yarn test
      after_script:
        - yarn add -D codacy-coverage
        - cat ./coverage/lcov.info | codacy-coverage

    - stage: release semantic-release
      script: skip
      deploy:
        skip_cleanup: true
        provider: script
        script: yarn semantic-release
