language: node_js
os: linux
cache:
  yarn: true
node_js: 12
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn lint
  - yarn build
  - yarn test
  - npx semantic-release
matrix:
  allow_failures: []
  fast_finish: true

