sudo: required
dist: trusty
cache:
  yarn: true
language: node_js
node_js: 12
addons:
  firefox: latest
before_install:
  # Start a display server where all graphical operations happens in memory
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
script:
  - yarn
  - yarn lint
  - yarn build
  - yarn test
  - npx cat ./coverage/lcov.info | npx codacy-coverage
  - npx semantic-release
matrix:
  allow_failures: []
  fast_finish: true

