language: node_js
os: linux
cache:
  yarn: true
node_js: 12
addons:
  firefox: latest
script:
  - yarn lint
  - yarn build
  - yarn test
  - npx semantic-release
matrix:
  allow_failures: []
  fast_finish: true

